[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[package.metadata.maturin]
requires-python = ">=3.7"
project-url =  { Source = "https://github.com/opencollector/tantivy-py" }

